import Header from './components/Header'
import Sidebar from './components/Sidebar'
import TopNav from './components/TopNav'
import './globals.css'
import Footer from './components/Footer'
import { headers } from 'next/headers'
export const metadata = {
  title: 'Next 13 blog',
  description: 'Generated by me',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const headersList = headers()
  const url = headersList.get('x-url') || ''
  console.log('🚀 ~ file: layout.tsx:19 ~ url:', url)

  return (
    <html lang='en'>
      <body className='bg-dirty text-dark'>
        <TopNav />

        {children}
        <Footer />
      </body>
    </html>
  )
}
